apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: fp-juletre
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image: ghcr.io/navikt/fp-juletre:1.0.2
  port: 8081
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  liveness:
    path: actuator/health
    initialDelay: 30
    timeout: 10
  readiness:
    path: actuator/info
    initialDelay: 30
    timeout: 10
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 128Mi
  ingresses:
     - "https://fpjuletre.dev.intern.nav.no"
